[theme]
base = "dark"
primaryColor = "#3987e5"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#151821"
textColor = "#e8e9ed"
font = "sans serif"

[server]
headless = true
runOnSave = false

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"
